version: '3.8'
services:
  npm:
    build: ./
    stdin_open: true
    tty: true
    volumes:
      - ./:/app

# docker-compose run npm init 
# docker-compose run --rm npm init 
# docker-compose run --rm npm install 
# docker container prune

